language: ruby
env:
  - DB=mysql
rvm:
  - 1.9
  - 2.1
  - 2.2
  - rbx-2.5.2
  - rbx-2.5.7
bundler_args: --without production
before_script:
  - mysql -e 'create database mysql_big_table_migration_test'
before_install:
  - gem update --system
services:
  - mysql
script:
  - bundle install
  - bundle exec rake test
cache:
  - bundler
os:
  - linux
  - osx
